### ISSUE TITLE
Slimify the README and create a Wiki

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#110]
I need someone who takes some of the basic and advanced topics out of the README to put them into a github wiki. 

Any takers? 

Ideally you'd have great knowledge of the English language, as well as a history of using Sub-Zero. You'd be added as a contributor to this repository.

**Comment by jbreuer95** [comment]
If no one does it, i can do it a few weeks from now when i am on vacation :)

**Comment by pannal** [comment]
I won't have time for this. Anyone?

**Comment by pannal** [comment]
Bump!

**Comment by ukdtom** [comment]
Considering the amount of people chiming in here, it's kinda sad :-1: 

I do not live up to the req. since I'm not native english, and only scratched the surface of this wonderful work so far, but I do indeed feel your pain, and can identify with it, since I coded a few plugin's myself.

So, not there yet, and so far just a POC, but was this what you had in mind?

[https://github.com/ukdtom/Sub-Zero.bundle/wiki](url)

Best Regards

dane22 aka UKDTOM

**Comment by pannal** [comment]
This looks awesome, mate!
You're the first to really tackle this issue, and you're doing well.

If you want to continue, I'd be happy to merge your fork and add you as a contributor!

**Comment by ukdtom** [comment]
PR created ;-)

And do fire away

/dane22

**Comment by pannal** [comment]
You're a collaborator now :)

**Comment by ukdtom** [comment]
Ready to go live here, but you must push the button, IMHO :+1: 

And you'll need to look on the following pages, where you should focus on the items in bold:
https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration
https://github.com/pannal/Sub-Zero.bundle/wiki/User-Guide

Best regards

/T

**Comment by ukdtom** [comment]
Also please notice my PM in the forums ;-)

**Comment by pannal** [comment]
Great work here! Closing this for now!
