### ISSUE TITLE
Request for PT-BR providers

### ISSUE THREAD

**Issue by leoheck** [pannal/Sub-Zero.bundle#127]
Hi, it is possible to inclode `http://legendas.tv/` as a subtitle provider? The  [LegendasTV.bundle project](https://github.com/BrutuZ/LegendasTV.bundle) from @BrutuZ should be doing that but the plugin isn't working for me.

**Comment by chopeta** [comment]
Thanks for submitting the issue Leo!

I also use pt-BR but to be honest I couldn't find enough cases where a sub were available in legendas.tv but not on Addicted, OS or Subscene and that's why I've reported #26 some time ago.

Anyway, that would be a good addition like any other provider that could provide better results, even if only for a specific language like this one. 

But I also think there are some complications, specially in regards to this provider.

You may want to follow this one:
* https://github.com/Diaoul/subliminal/pull/513

If I understood correctly, this could end up here in SZ when #86 is completed, but I think @pannal it's the right person to confirm this.

At the end of the day, maybe it makes more sense for the provioders to be added directly on Subliminal instead of here on SZ. What do you think @pannal ?

**Comment by leoheck** [comment]
I just found and installed sub-zero yesterday when I was installing my new NAS. Differently from the PC, subtitles were making me crazy. So, I should try sub-zero a bit to see if it works well with _pt-br_. Thank you for the answer @chopeta and let see what @pannal have to say. Thank you guys!

**Comment by DrClimax** [comment]
www.legendasdivx.com is also a good spot for PT-BR and PT-PT.

**Comment by pannal** [comment]
Yeah there will be PT-BR providers with subliminal 2.0 (when the PR is merged by @Diaoul), together with the other addons subliminal received (napiprojekt, subscenter)

**Comment by BrutuZ** [comment]
Not sure if there is a particular reason for it or the fact just passed by unnoticed, but Subliminal has been updated with support for Legendas.tv ([Repo](https://github.com/Diaoul/subliminal/tree/master/subliminal/providers)) 👍

**Comment by pannal** [comment]
Fixed in 2.0
