### ISSUE TITLE
The character "å" in subtitles are replaced with other characters

### ISSUE THREAD

**Issue by critaL** [pannal/Sub-Zero.bundle#205]
Hey!
Sub-Zero works wonders, however i am having issues with the character "å". It's being replaced with [ and |  which is kind of weird. I mainly watch movies with swedish subtitles and the character "å" is very common. I don't really know what info i should provide but just let me know and i will do my best.

OS: Ubuntu Server

**Comment by pannal** [comment]
Could you please set SZ's log level to DEBUG and manually download a subtitle where this happens, from the new manual menu, then attach the log here?

**Comment by critaL** [comment]
[com.plexapp.agents.subzero.log.zip](https://github.com/pannal/Sub-Zero.bundle/files/609614/com.plexapp.agents.subzero.log.zip)

**Comment by pannal** [comment]
Hm yeah. It decides to use UTF-8 instead of latin-1.
I'd have to run some tests, but I can fix this for the next release.

**Comment by critaL** [comment]
Amazing! Let me know if you need any more info or any help :)

**Comment by pannal** [comment]
Well I could add a test branch with a possible fix. Would you be willing to check it out? (See the Wiki on how to switch to developer mode)

**Comment by pannal** [comment]
Did you see my last comment?

**Comment by pannal** [comment]
Hmm. I've just tried fixing the problem by trying latin-1 first.

Unfortunately that won't work and produce even worse results. Do you have the problem for every swedish subtitle it downloads? I can't imagine that.

For example the swedish version of [this subtitle](http://www.addic7ed.com/serie/Castle_%282009%29/1/1/Flowers_for_Your_Grave) decodes in latin-1 and UTF-8, but in latin-1 it's totally garbled, whereas in UTF-8 everything is fine except the one in `Vem är den hjärt-blÃ♪dig detektiven,`, which seems to be an error on the subtitle creator's part.

**Comment by pannal** [comment]
I've just had a look at your particular subtitle file. If you download it from https://www.podnapisi.net/subtitles/sv-ex-machina-2015/F7w8 and compare it to the one SZ downloaded, is there a difference?

Because when I look at the file, the characters seem correct and it even says "utf-8" in the file name.

**Comment by ukdtom** [comment]
Been scandinavia (Danish) I also speaks/reads swedish

The Podnapsi subtitle is defective, since the entry below is wrong:

`9
00:02:30,501 --> 00:02:35,500
- Släpper du av mig här?
- Jag fĺr inte komma närmare byggnaden.`

In above, it's the word: `fĺr`

As such, I suspect that SZ is doing the best it can, but if the source sub claims to be in utf-8, and is in utf-8, but was converted to that incorrectly, there's nothing SZ can do about that!

/dane22

**Comment by ukdtom** [comment]
And @pannal I still recommend you take a peak @ the chared module I use in my [SRT2UTF-8](https://github.com/ukdtom/SRT2UTF-8.bundle/tree/master/Contents/Libraries)
