### ISSUE TITLE
Automatic Log packager improvements

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero.bundle#271]
- External IPs aren't always accessible via a local network (Also display the local IP log URL)
- try to detect HTTPS

**Comment by ukdtom** [comment]
From the framework:
`Network
Network.Address
Returns the server’s IP address. Unless the server is connected directly to the internet,
this will usually be a local IP address.
Return type str
Chapter 6. API ReferencePlex Plug-in Framework Documentation, Release 2.1.1
Network.PublicAddress
Returns the public IP address of the network the server is currently connected to.
Return type str
Network.Hostname
Returns the server’s hostname.
Return type str`

**Comment by pannal** [comment]
Yes, I know. I just can't get any info about the current request, so I don't know whether the user is connecting from inside or outside his network. The public IP isn't always routed correctly inside a local network.

**Comment by chopeta** [comment]
Can we try with Network.Hostname? I have a guess that it would resolve it auto-magically.

Since I am still using PMS 0.9.x I can't access the WebGUI directly so Plex always left a link for me on the webGUI so I can access my server directly. This link is always automatically set properly depending on my current location (inside or outside my network). The hostname on the link is the part that changes and it something Plex generated which includes the IP address of the machine + something else from Plex internals. That's where my guess come from... ohhh it always came with HTTPS (I guess it has something to do with my PMS secure settings).

Here's the URL generated by PlexWeb when I am trying to access my server from outside my network (IP is masked, noticed how they replace the dots with "-" so the IP can be used in the hostname):

https://18x-x-2xx-xx.a99dbe7d8c824ca6920fa1436115bedb.plex.direct:32400/web/index.html#!/settings/server

And here's the one when I am trying to access from inside my local network:

https://192-168-2-12.a99dbe7d8c824ca6920fa1436115bedb.plex.direct:32400/web/index.html#!/settings/server

Hope it helps.

**Comment by pannal** [comment]
Network.Hostname returns the local hostname, which won't help with external access, only local.

**Comment by pannal** [comment]
I think I fixed that in the current version

**Comment by pannal** [comment]
Fixed in 2.0 develop.
