### ISSUE TITLE
Can't update Sub-Zero in WebTools since it's branch

### ISSUE THREAD

**Issue by dny238** [pannal/Sub-Zero.bundle#278]
Can you make Sub-Zero it's own project now? Aren't ever merging it back into Subliminal, right?

https://github.com/ukdtom/WebTools.bundle/issues/315#event-1075420369

**Comment by ukdtom** [comment]
Sub-Zero is part of the Official directory!

If using that, all is good.

If using Sub-Zero developer/beta branches, then follow the Wiki
https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner

**Comment by ukdtom** [comment]
Ups...hit close button by a mistake ;-)

**Comment by pannal** [comment]
Hmm. Is this still an issue? I don't recommend being on a Dev branch because those are usually unstable. 

Please use the official channel installer in plex. If you want to test Dev, follow the wiki on how to do that. 

As SZ is in the official channel repository, webtools isn't officially supported by me.

**Comment by pannal** [comment]
May work again, as I've re-created branch develop-1.5

**Comment by pannal** [comment]
@dny238 is this fixed now?

**Comment by pannal** [comment]
Please reopen if needed
