### ISSUE TITLE
Nordic characters showing other characters (v2)

### ISSUE THREAD

**Issue by janpfo** [pannal/Sub-Zero.bundle#296]
I'm using v2 with "fix OCR errors" enabled, but it still can't show ÆØÅ the correct way. Å becomes Ã¥, Ø becomes Ã¸ Æ becomes Ã¦. The subtitles are from OpenSubtitles. It worked in the last stable, if I wasn't using Podnapsi.

**Comment by pannal** [comment]
OK. That may be actually due to the subtitle uploader's fault to convert the encoding correctly.

RC10, which is due tomorrow, will incorporate a possible fix for this. If that doesn't fix it, please holler again, or, better, [join our slack](https://szslack.fragstore.net)) so we can talk about it indepth.

**Comment by pannal** [comment]
RC10 is out, please report back!

**Comment by pannal** [comment]
RC10 got pulled because of a bug. Please use RC10.1

**Comment by janpfo** [comment]
Tested one subtitle now, looks like it's good 👍 Now I have to delete all my subtitles and download them again :)

**Comment by pannal** [comment]
Nope. Go to the advanced menu and hit "re-apply all mods".

**Comment by pannal** [comment]
Re-downloading is the most safe way, though. You can try the advanced option first.
