### ISSUE TITLE
Messed up language settings after upgrade

### ISSUE THREAD

**Issue by vBm** [pannal/Sub-Zero.bundle#308]
SZ got auto upgraded to latest release. After upgrade i've noticed that settings for `Subtitle Language (3)` changed from `Croatian` to `Ukrainian` for some reason. (I'm using `English`, `Serbian`, `Croatian` and then `bs;bos` as additional languages.

I guess that this bug is introduced by splitting `Serbian` into `Serbian (Latin)` and `Serbian (Cyrillic)` and forgetting to change the value for the language. `Croatian` used to have option value of `45` but now it's `47`.

While not being a big issue, it's still one when you see wrong language rendered on your show :P 

Unfortunately i don't have backup of old settings.
Thanks in advance.

**Comment by pannal** [comment]
Yeah. I was unaware of plex storing the enum values by their numerical index instead of by their values (which is very weird to me).

I'm sorry, nothing to do about that anymore.

**Comment by pannal** [comment]
Anyone with languages configured that are in this list, will have to re-configure them:
```
  "sk":"Slovak",
  "sl":"Slovenian",
  "es":"Spanish",
  "sv":"Swedish",
  "th":"Thai",
  "tr":"Turkish",
  "uk":"Ukranian",
  "vi":"Vietnamese"
  "hr":"Croatian",
```

**Comment by vBm** [comment]
It's not that big of a deal. Fixing is done in ~2 seconds :)

**Comment by viking1304** [comment]
btw. you do not need both bs and bos in additional languages. Only one is enough.

You might consider something like this instead of what you are using:

![image](https://user-images.githubusercontent.com/28989870/27946263-362b5a7a-62f1-11e7-9bb8-64766f938473.png)

If you do not need Serbian (Cyrillic) subtitles you can only left en in additional field.

Whatever you do, do not turn off "Treat IETF language tags as ISO 639-1 (e.g. pt-BR = pt)" or all your Serbian (Latin) subtitles will be treated as unknow by Plex.  

If you still have issues with "unknown" subtitles, reason is Plex local media scanner in combination with your decision to keep subtitles in same folder as media files. Turn it of for both movies and series or change SZ settings to move your subtitles in a separate folder,

![image](https://user-images.githubusercontent.com/28989870/27946523-829cd20c-62f2-11e7-90b5-0621d10d3e34.png)

![image](https://user-images.githubusercontent.com/28989870/27946803-9e919adc-62f3-11e7-9950-c4a7063b0636.png)

**Comment by vBm** [comment]
> btw. you do not need both bs and bos in additional languages. Only one is enough.

good to know, thanks.

I'm using English as main subs because i always watch movies/shows like that but i need exYu langs for my brother :)

**Comment by SvenErik1968** [comment]
My third language option that was set to Thai before the latest version got changed to Spanish. But several days after I changed it back to Thai, it keeps downloading subtitles in Spanish.

**Comment by pannal** [comment]
Can you set the correct settings again, please? I'm guessing this is auto update related.

**Comment by pannal** [comment]
This will finally be "fixed" by resetting the three main language settings to default with the next release. Too many problems popped up because of this.
