### ISSUE TITLE
"No current subtitles in storage" when they do exist

### ISSUE THREAD

**Issue by enchained** [pannal/Sub-Zero.bundle#375]
Synology DSM, latest PMS. Fresh install from plex web, never used before.

Plex says there are English srt subtitles (external in one case, and embedded in another). I watched both shows with subtitles, then configured Sub-zero (agent and settings). Then I opened recently played in the channel and both of those episodes said "No current subtitles in storage" for English. 

When I hit the Refresh, my second language subs were downloaded for one of the episodes (no translations exist for the other). But info about existing English subs stays ignored. 

In another case with not-recognized embedded str (that plex does see) I hit a Forced Refresh, it downloaded new English subtitles, and now plex sees TWO English subtitles - preexistent embedded and downloaded external. What's wrong?

[Here is the log](https://pastebin.com/FcsT0L8D) with some S03E06 with embedded English srt (labeled as English in mediainfo), and S02E01 with external (no language showing, just filename.srt), both not detected. I restarted Sub-zero, turned on debug level, refreshed those two episodes, and saved the log. 

S03E06 case results: nothing English is downloaded in history (second lang subs were downloaded in the previous refresh), English still says "No current subtitles in storage". 

S02E01 case results: English subtitles downloaded in history, Sub-zero sees those new ones, filesystem has two files now: old filename.srt and downloaded filename.en.srt

Am I doing something wrong? Or is it expected behavior? Thanks for any help.

**Comment by pannal** [comment]
Can you make a screenshot of your SZ settings? Then I can answer your questions :)

**Comment by enchained** [comment]
My settings: https://imgur.com/a/bHIzD Thanks

**Comment by pannal** [comment]
Hey, the existing subtitle on disk is not recognized by Sub-Zero. That's intended as SZ doesn't have any source information about that file. SZ is only talking about its internal subtitle storage it keeps for all downloaded subtitles, there.

There has been a release recently possibly dealing with some of the issues you were mentioning.

If you used the official channel repository for installation, it should've updated by now, automatically.

**Comment by enchained** [comment]
Then why are those options exist in the settings, if those are not recognized by Sub-Zero? What do they do?

* Don't search for subtitles if there are embedded subtitles inside the media file (MKV/MP4)?
* Don't search for subtitles if they already exist on the filesystem (metadata/filesystem)?

I have them checked and sometimes it still ignores existing subtitles and downloads a duplicate (especially when embedded). 

Or it can detect subtitles using those options, but won't say so in its menu and still will say "No current subtitles in storage" instead?

**Comment by pannal** [comment]
1. You're using the older version, please upgrade if you're not on 2.0.29.1756

Let me explain:
If you already have external or embedded subtitles for your media, those two options will determine whether SZ will search for subtitles or not.
It will add the external ones that it detects to the plex media metadata so you can use them.

The menu is a different thing - when SZ downloads a subtitle, or sees a media item for the first time, it creates an internal storage item, which keeps track of the subtitle it may have *downloaded* for you, its score, and where it came from. That is to determine whether a new subtitle it found, using the scheduled tasks, is better than the one it already downloaded.

The SZ internal subtitle storage also holds the original subtitle content, so the modification framework can work on the content, while retaining reversibility.

If you see "No current subtitles in storage" that simply means that SZ doesn't know about any subtitle it downloaded for that media file. That doesn't include already pre-existing external or embedded subtitles. The menu is for modifying subtitles SZ has downloaded before.

Probably with release 2.1, SZ will be able to import already pre-existing external subtitles into its local storage to enable the subtitle modification framework for those, too.

If SZ downloads a subtitle, and you think it did so wrongly (because there already is an existing embedded or external one, and you have the corresponding setting enabled), please tell me.

There have been changes to the detection of embedded subtitles in the current version, so please upgrade.

I hope that gives you some insight on how SZ operates.

**Comment by enchained** [comment]
Thank you for the explanations! I see, so there's no way to actually see whether SZ detected pre-existing subs, other than reading logs. The menu thing was a little confusing.

It looks like plex auto-updated it to 2.0.29.1767. I'll report if I run into detection problems on this version.
