### ISSUE TITLE
Subtitles not always downloading

### ISSUE THREAD

**Issue by QuintenJustus** [pannal/Sub-Zero.bundle#406]
Hi!
I have used sub-zero for quite a while now, it's perfect for me. Solid coding!
But I have an issue, my series folder won't download subtitles on it's own. I tried scanning files, deleting and reinserting the files, refreshing metadata. Nothing worked, the only fix seems to be to enable the "on media playback: search for missing subtitles (refresh item)" selected: hybrid plus. And manually clicking every episode so it forces it to download. Am I missing something? Or is it a common issue?
Looking forward to your response!

**Comment by QuintenJustus** [comment]
PS: Movie subtitles all seem to be downloading just fine.

**Comment by pannal** [comment]
Hmm, sounds weird. Is the plugin enabled for your TV series library? Can you attach logs?

**Comment by QuintenJustus** [comment]
If you mean via agents, it's enabled yes, I'd be happy to include logs, but where do I download it?

**Comment by pannal** [comment]
[First entry of the wiki](https://github.com/pannal/Sub-Zero.bundle/wiki/Logs)

**Comment by QuintenJustus** [comment]
[Logs_171212_21-04-10.zip](https://github.com/pannal/Sub-Zero.bundle/files/1553117/Logs_171212_21-04-10.zip)

**Comment by pannal** [comment]
Thank you. Please set the logging verbosity to DEBUG in SZ's settings and refresh a TV series media item. Also please wait for the latest bugfix update to arrive (or [go the manual route](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation)).

**Comment by QuintenJustus** [comment]
[Logs_171213_22-31-38.zip](https://github.com/pannal/Sub-Zero.bundle/files/1557136/Logs_171213_22-31-38.zip)

**Comment by pannal** [comment]
There's nothing wrong in there. It searches for your TV series and doesn't find matching subtitles, mainly because your file naming isn't sufficient - you're lacking the crucial info of source/format (BluRay, WEB-DL etc.), or the release group, to being able to match with a score of 337.

If you use sonarr or filebot for renaming your files, upcoming version 2.1 will come in handy, as it will have support for that.

The other option is to lower the TV score massively, but you'll run into bad subtitles then.

As far as I can tell from the information I have, the fact, that you got subtitles for an episode after using hybrid mode, was a coincidence.

**Comment by QuintenJustus** [comment]
Ah! That explains a lot, I manually renamed most of them to keep order. Thanks a lot!
