### ISSUE TITLE
Sub Zero doesn't Download subtitle even if they are in Opensubtitle / addicted

### ISSUE THREAD

**Issue by Tomp0uce** [pannal/Sub-Zero.bundle#412]
Hi there,
Firstly I would like to thank you for your great work! Good job guys this thing is so good! :+1: 

I installed Plex on my nas last week and discovered Sub zero! How could I didn't knew about it before!! :) 
But I have some problems. 
Indeed on some Tv Shows of the same show stored on the same folder in the NAS and managed by Sonarr, for some episodes the subtitles are downloaded very well but for other episodes they are not downloaded at all even if they are on opensubtitles.org or addic7ed.com. I even checked with VLC Sub and the subtitle are found with the hash calculation without problem. For example for fear the walking dead season 3, all the subtitle are downloaded except for episode 9 10 11 14 15 and 16.

And on some TV shows sub zero download no subtitle for the whole folder. It happen mostly on TV show where there is the year of the show (like The Flash (2014) - S02E02 - HDTV-720p, Archer (2009) - S07E02 - HDTV-720p...) or some local language addition of the show (like House of Cards (US) - S02E01 - SDTV) but also on some shows where there is nothing except the name of the TV show on the title.

I have attached the log in debug mod.

Thank you for the attention you will provide to my request.
Best Regards!

**Comment by pannal** [comment]
Hey,

The log doesn't show a hell of a lot as it's set to only display errors. Please set SZ's logging via its settings to DEBUG, then refresh some of those episodes again. Afterwards, please use the get my logs link from SZ's advanced menu and attach the zip file.

I'm noticing a fair amount of errors inside the log you posted - most of them errors from opensubtitles (they may have blocked you if you reached the limit) and some timeout errors when SZ tries to reach the API of your PMS. Is your NAS under heavy load at times or have you been adding many media files since you set up everything?

I can only guess without a good debug log.

**Comment by Tomp0uce** [comment]
Dear Pannal,
Thank you for your help.

I though i had enabled the debug not but it didn't seem so. So here are the logs with the debug mode on. The info for my examples should be in com.plexapp.agents.subzero.log.1 and com.plexapp.agents.subzero.log
For the example, I have asked Plex to refresh metadata of those episodes : 
Black Mirror - S01E01 - SDTV
The Americans (2013) - S01E01 - SDTV
The Americans (2013) - S01E02 - HDTV-720p
Grey's Anatomy - S14E03 - SDTV
House of Cards (US) - S03E04 - HDTV-720p

All those episode don't have embedded subtitles, and by using VLC sub on VLC I can find the correct french subtitles (with opensubtitles source) even with the hash option on some episodes. 
But with plex + subzero nothing is found. 

Do you see something specific in the log? 

I have also 2 others questions : 

- Is it possible to force the download of french subtitle for files that have embedded subtitles in english? 
For example, in the episode Marvel's Daredevil - S01E05 - HDTV-720p I have embedded english subtitles. In VLC sub, i am able to find French subtitles with hash option on opensubtitles.org. 
I have enabled the following options on subzero menu : 
Subtitle Language (1) French 
Subtitle Language (2)  None
Subtitle Language (3)  None
Restrict to one language (skips adding ".lang." to the subtitle filename; only uses "Subtitle Language (1)")

I have disabled the following option
 Embedded subtitles: Treat "Undefined" (und) as language 1
Don't search for subtitles if there are embedded subtitles inside the media file (MKV/MP4)?
 Don't search for subtitles if they already exist on the filesystem (metadata/filesystem)?

But with those options I can't achieve to download the subtitles in french for this episode.

- Last question, is there a way to remove the .lang. on the subtitle filename but download a second language with the .lang. in the filename? Will I need to do my custom script?

Thank you by advance for the attention you will have for my requests.

Best regards

**Comment by Tomp0uce** [comment]
[Logs_171222_23-11-40.zip](https://github.com/pannal/Sub-Zero.bundle/files/1583485/Logs_171222_23-11-40.zip)

**Comment by Tomp0uce** [comment]
I closed the topic with a misclick sorry, I reopen It

**Comment by pannal** [comment]
* Black Mirror S01E01 has been downloaded by SZ as `/volume1/video/Serie/Black Mirror/Saison 1/Black Mirror - S01E01 - SDTV.srt` from http://www.addic7ed.com/updated/8/56278/11
* The Americans S01E01 has been found on OpenSubtitles but has been ignored as the format doesn't match (SDTV vs. HDTV) - this may be considered a bug and I'll add a ticket for this. I guess the same happened for E02.
* Grey's Anatomy: The same issue as The Americans
* House of Cards on OpenSubtitles has been rightfully ignored by SZ because its FPS doesn't match your file (23.976 vs. 25fps); It doesn't match on Addic7ed, because the format doesn't match.

For your first question: It should work as-is, for your use-case. I don't see the Daredevil search in your logs, so I can't tell you why it didn't download it.

For your second question: Not at the moment, no, sorry. For Sub-Zero version 2.2 advanced provider configs are planned, which would allow you to do that.
