### ISSUE TITLE
[Feature request] Fix all caps subtitles

### ISSUE THREAD

**Issue by BeyondEvil** [pannal/Sub-Zero.bundle#439]
This is something that goes along the lines of `Fix common whitespace/punctuation issues in subtitles` and `Fix common OCR errors in downloaded subtitles`.

Let's call it "Fix subtitles that are in all caps"
Some subtitles (mostly embedded ones, honestly) are sometimes in all caps. Highly annoying.

This could be accomplished with the naive approach and fix it with regex (re) or even a combination of pythons string-functions. Or with the use of one of the many NLP libraries available for python.

I'd be happy to contribute, but I would need some guidance to get started.

**Comment by pannal** [comment]
Hmm, first we'd need some sort of detection mechanism for all-caps. I guess the first 10% of the subtitle would suffice.

Then you'd plug in a whole-file-modifying modification into SZ's mod framework and we'd be good to go. You could start off by looking at the [simple color plugin](https://github.com/pannal/Sub-Zero.bundle/blob/master/Contents/Libraries/Shared/subzero/modification/mods/color.py), which does whole-file-modifaction.

The SZ mod framework knows about two types of mods - whole file and per-line. Whereas per-line is exactly per line, not per entry. So one mod sees 

`hello mister` as one line and
`how are you` as another one

out of the subtitle entry
```
hello mister
how are you
``` 

Whole-File-Mods get passed None as the parameter `content`, single line mods get the line content there. The whole file can be accesses via parent.f as you can see from the color modification.

The mod framework isn't really third-party-developer-friendly as of now, because of lack of documentation and it needs a rewrite here and there. Should be easy enough to understand with a little bit of time on your hands.

**Comment by BeyondEvil** [comment]
I can start to look around and try to get a feel for the code.

Will the naive approach work as a MVP?

That is, `WE SHOULD GO TO SWEDEN!` will become `We should go to sweden!` instead of the proper `We should go to Sweden!`

My experience with NLP is limited. Regardless it shouldn't be too difficult to do a 2.0 with NLP once the detection and processing mechanisms are in place.

**Comment by pannal** [comment]
Well sure, we'll need to make sure that it only applies to western languages, though.

**Comment by pannal** [comment]
This has been done.
