### ISSUE TITLE
[Sub-Zero/2.5.3.2452] SearchAllRecentlyAddedMissing error, ZeroDivisionError

### ISSUE THREAD

**Issue by xasbo** [pannal/Sub-Zero.bundle#496]
I installed the plugin a few days ago, did one library-level refresh to get some content updated, and then left the scheduler to pick up the rest over the next couple days. It's been a bit over two days now and I noticed that most content doesn't have subs yet, so I started poking around. I found in the log that, for some reason, when SearchAllRecentlyAddedMissing runs, it fails with a ZeroDivisionError while calculating the progress percentage - which implies that it got this far while not having any items to search for.

Manually refreshing individual items works correctly, but the log includes an error for that operation as well. However, that's a different error, saying it was getting a ProtocolError while interacting with the OpenSubtitles API. I did end up getting subs where I had none before, though, so I'm not sure what's going on there.

The only special Plex configuration that I can think of is that my Plex AppData folder is not on the OS drive, but the Sub-Zero logs correctly reflect the re-located path and seem to be locating assets just fine. This was configured directly through the server configuration.

The latest log file is attached. Can someone tell me what I'm doing wrong?

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/1913706/com.plexapp.agents.subzero.log)

**Comment by pannal** [comment]
Looks like everything is fine, except that I didn't properly check for a zero value.

The SearchAllRecentlyAddedMissing task scans through all media files SZ has a storage for (e.g. it has "seen" those before), but not all of those items are eligible for the task based on age. This results in the `items_searching` number to dynamically decrease while it runs, and you're the first to have an item skipped at the end of the run, resulting in `items_searching` being zero and throwing a `ZeroDivisionError`.

This will be fixed in the upcoming release. Other than that I can't find anything else in your logs, as SZ is not set to log_level DEBUG.

**Comment by xasbo** [comment]
Thanks for the quick reply, I appreciate it. I changed log_level to DEBUG, applied the changes from e961c8d3aa004544ac26868ea154fe082b68946c to my local copy, and restarted the server. I'll see what falls out in the next scheduled run.

Based on the FAQ, I was expecting the scheduler to have run a full search at some point, rather than just against recently added items. Is that task name a misnomer, or is another one supposed to be running periodically to check the entire library at some point?
