### ISSUE TITLE
Deleted subtitle sticks in PMS - ( again )

### ISSUE THREAD

**Issue by leelouch** [pannal/Sub-Zero.bundle#512]
*** this is a clone of this ticket Deleted subtitle sticks in PMS #276 *** 
Sorry to open it again 

Hi, it seems I have the same problem in Sub-Zero 2.5.4.2527
xml info before deleting the SRT is https://pastebin.com/QWZ2K197
xml info after deleting the SRT is https://pastebin.com/2MWmEwrs
any idea, please ?
thanks

**Comment by pannal** [comment]
Did you refresh the item's metadata afterwards? Plex should notice the abscence of the file and remove it from the list.

Otherwise you can use WebTools I think (@ukdtom?) to remove the missing subtitles.

For further investigation, I'll need a DEBUG log file after a metadata refresh of the item in question.

**Comment by ukdtom** [comment]
Correct, unless if on Mac, where it's sadly broken at the moment

**Comment by leelouch** [comment]
I think I did , I will try again and provide log

**Comment by leelouch** [comment]
Ok, I tried to reproduce the issue, but now after the reloading metadata, Plex downloaded again the sub !.
You can ignore the ticket for now! it it happen again I will update the ticket. 
In my case what happend is that Plex refused to play the film by issuing an error ( founded in the log ):
 **file not found on the missing srt** 
Thanks.
