### ISSUE TITLE
Does not "Automatically extract and use embedded subtitles upon media addition"

### ISSUE THREAD

**Issue by cphmichael** [pannal/Sub-Zero.bundle#598]
I am trying to setup SZ to ‘Automatically extract and use embedded subtitles upon media addition (with configured default mods’.

It works if I from the menu click ‘Extract missing English embedded subtitles’, but it does not work Automatically upon media addition.

As pannal commented on Sep 12 I have enabled:
* Embedded streams: Treat "Undefined" (und) as language 1
* Don't search for subtitles of a language if there are embedded subtitles inside the media file (MKV/MP4)?

Please look at the uploaded “The Rookie - S01E05”

It says "Extracting stream 2 (en) of The Rookie - S01E05 - The Roundup.mkv" but SZ does not save the subtitle to the folder.

There is an “ERROR (model:205) - Cannot read model from /config/Library/Application Support/Plex Media Server/Metadata/TV Shows/.......

Maybe that is the reason why SZ don’t store the embedded subtitles.

In the log it says “Creating new subtitle storage for: 2750”

Does that refer to “Searching for matches for ‘id’: ‘2748’” in the first line, because then it refers to a wrong ID.

[The Rookie - S01E05.txt](https://github.com/pannal/Sub-Zero.bundle/files/2610623/The.Rookie.-.S01E05.txt)
[The Rookie - Media Info.txt](https://github.com/pannal/Sub-Zero.bundle/files/2610624/The.Rookie.-.Media.Info.txt)

**Comment by pannal** [comment]
Can you set the log level of SZ to DEBUG (bottom of the settings), then refresh an episode in question and post your logs?

**Comment by cphmichael** [comment]
I have enabled:
* Log subtitle modification (debug)
* Log to console (for development/debugging)

After that I "Restarted the Plugin"

Downloaded:
* The Rookie - S01E02 - Crash Course.mkv

There is no subtitles in the folder

Here is the full log:
[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2612227/com.plexapp.agents.subzero.log)

And the Media Info:
[Media Info.txt](https://github.com/pannal/Sub-Zero.bundle/files/2612228/Media.Info.txt)

**Comment by pannal** [comment]
Please set SZ's log level to DEBUG: https://github.com/pannal/Sub-Zero.bundle/wiki/Sub%E2%80%90Zero-Configuration#advanced-configuration

**Comment by pannal** [comment]
"How verbose should the logging be?" is the setting.

**Comment by cphmichael** [comment]
Here is the DEBUG log:

[com.plexapp.agents.subzero.log](https://github.com/pannal/Sub-Zero.bundle/files/2612408/com.plexapp.agents.subzero.log)

And my Sub-Zero Subtitles Setting in case you need it:

![sub-zero subtitles settings 1](https://user-images.githubusercontent.com/45288008/48970475-f0801600-f00c-11e8-83b1-aeeff0ed1647.png)
![sub-zero subtitles settings 2](https://user-images.githubusercontent.com/45288008/48970476-f4139d00-f00c-11e8-97d3-044085a02c81.png)
![sub-zero subtitles settings 3](https://user-images.githubusercontent.com/45288008/48970480-fbd34180-f00c-11e8-80aa-4c52e9a0312d.png)
![sub-zero subtitles settings 4](https://user-images.githubusercontent.com/45288008/48970482-0097f580-f00d-11e8-8835-1e12c41f3f5e.png)
![sub-zero subtitles settings 5](https://user-images.githubusercontent.com/45288008/48970488-07bf0380-f00d-11e8-8ec7-da598176ac3a.png)
![sub-zero subtitles settings 6](https://user-images.githubusercontent.com/45288008/48970489-0c83b780-f00d-11e8-801b-ee69eaa8f731.png)

**Comment by pannal** [comment]
OK, this is a bug.

Because you have `Don't search for subtitles of a language if there are embedded subtitles inside the media file (MKV/MP4)?` set, the subtitles get extracted but never set as current (never actually activated/written to disk).

This is fixed in [develop-2.6](https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.6.zip), if you want to test it (please refer to the [wiki on how to install the dev branch](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation)). The fix will be released with the upcoming bugfix release.

Thanks for posting your logs and reporting this issue.

**Comment by pannal** [comment]
OK, this is a bug.

Because you have `Don't search for subtitles of a language if there are embedded subtitles inside the media file (MKV/MP4)?` set, the subtitles get extracted but never set as current (never actually activated/written to disk).

This is fixed in [develop-2.6](https://github.com/pannal/Sub-Zero.bundle/archive/develop-2.6.zip), if you want to test it (please refer to the [wiki on how to install the dev branch](https://github.com/pannal/Sub-Zero.bundle/wiki/Developers-Corner#manualdevelopmenttesting-installation)). The fix will be released with the upcoming bugfix release.

Thanks for posting your logs and reporting this issue.
