### ISSUE TITLE
Get my Logs not working

### ISSUE THREAD

**Issue by mouzzampk2014** [pannal/Sub-Zero.bundle#696]
Hi, when I click on `Get my logs` I get `cannot reach this page`. 
Thank you

![1](https://user-images.githubusercontent.com/44548525/68246608-09f95280-0011-11ea-8aee-44047dc1cba6.jpg)

![2](https://user-images.githubusercontent.com/44548525/68246610-0a91e900-0011-11ea-8f24-2c099abab0a2.jpg)

**Comment by pannal** [comment]
This is Kitana right?

**Comment by mouzzampk2014** [comment]
> This is Kitana right?

Yes it's Kitana

**Comment by pannal** [comment]
I'll have a look :)

**Comment by mouzzampk2014** [comment]
> I'll have a look :)

Thank you please :)

**Comment by cphmichael** [comment]
I have the same log problem.

For me I think Kitana gets IP-confused because I connect to my server remote via VPN.

My Plex servers local address is 10.60.154.11 but after a log timeout, the Kitana website says:

* This site can’t be reached - 130.225.98.253 took too long to respond.

and that is the VPN external IP-address

**Comment by mouzzampk2014** [comment]
For me, Kitana running on 192.168.1.52 and Plex is on 192.168.1.165 and I'm not using any vpn between these two devices.

**Comment by pannal** [comment]
Yeah, SZ itself tries to find the proper IP and Kitana just redirects to the old Get My Logs URL that SZ returns.

I'll change that and have Kitana actually proxy the file when I can find the time. That'll circumvent any issues there.

**Comment by pannal** [comment]
This is Kitana-specific now, closing!

**Comment by mouzzampk2014** [comment]
Thank you so much. Much appreciated
