### ISSUE TITLE
Sub-zero not showing up under PMS plugins or agents

### ISSUE THREAD

**Issue by abshafique** [pannal/Sub-Zero.bundle#703]
Hi,
I am running Version 1.18.2.2058 and just downloaded and copied Sub-Zero.bundle to the plugins folder in my Windows 10 machine. I do have WebTools installed and that works so I am wondering why subzero is not even showing up as a plugin or agent. I have tried restarting PMS and my PC. Please advise. Thanks!

**Comment by vhristev** [comment]
I have the same issue with older version 1.15.8.1198-eadbcbb45 installed on Synology. 

I dont see any clue plug is installed and i dont know how to troubleshoot

**Comment by pannal** [comment]
Please be sure to check https://github.com/pannal/Sub-Zero.bundle/wiki/Installation and https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ. 

Did you place SZ in the proper folder? Did the download complete fully or are you missing files?

**Comment by vhristev** [comment]
Yep i follow the FAQ and I'm sys admin ... files are there i download the zip from repo and unzip it. Then i did the same thing because i assume zip is corrupted the same behavior.

`vhristev@ds15:~$ cd /volume1/Plex/Library/Application\ Support/Plex\ Media\ Server/Plug-ins/
vhristev@ds15:/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins$ ls -l
total 0
drwxr-xr-x 1 plex users  16 Dec 19  2017 Services.bundle
drwxr-xr-x 1 plex users 110 Jan  6 16:21 Sub-Zero.bundle
vhristev@ds15:/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins$ ls -l Sub-Zero.bundle/
total 80
-rwxr-xr-x 1 plex users 63590 Jan  6 16:21 CHANGELOG.md
drwxr-xr-x 1 plex users   174 Jan  6 16:21 Contents
-rw-r--r-- 1 plex users  2300 Jan  6 16:21 LICENSE
drwxr-xr-x 1 plex users   588 Jan  6 16:21 Licenses
-rw-r--r-- 1 plex users  9599 Jan  6 16:21 README.md
vhristev@ds15:/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins$ ls -l Sub-Zero.bundle/Contents/
Code/                            DefaultPrefs.json                Info.plist                       Libraries/                       Resources/                       Strings/                         advanced_settings.json.template`

**Comment by pannal** [comment]
Weird, a PMS restart after that should bring up SZ under agents or Settings->Plugins. 
Can you attach your `Plex Media Server\Logs` folder (including `PMS Plugin Logs`)?

**Comment by vhristev** [comment]
I'm really sorry. It seems i mess up my entire volume on which current Plex is installed. Folder i point its from 2017 and when i search for the logs i notice its from 2017. my current volume where Plex is installed is /volume2 but i put the bundle in /volume1 . I move it to the correct place and now i see it. Sorry for bothering you guys.

**Comment by pannal** [comment]
np :)
